name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run unit + component tests (Vitest + RTL)
        run: npm run test -- --run

      - name: Run Playwright e2e
        run: npx playwright install --with-deps && npx playwright test

      - name: Run linting
        run: npm run lint

      - name: Run type check
        run: npx tsc --noEmit